// import alex from "/alex-varela-OEhWh_xz_JM-unsplash.jpg"
export const RWData = [
  {
    img: "/images/create.png",
    img2: "/images/create.png",
    title: "cr8Vibe Media",
    link: "https://cr8vmedia.vercel.app/",
    // action:"",
    category: "Frontend",
    desc: "NextJs, Tailwindcss, react Icons.",
  },
  {
    img: "/images/growthclub.png",
    img2: "/images/growthclubsnap.png",
    title: "Growth Club",
    link: "https://growthclub.life",
    category: "Frontend",
    desc: "chart.js, formik, tailwindcss, yup, react-table, NextJS, TailwindCSS, Redux toolkit, RTK Query.",
  },
  // {
  //   img: "/images/techdia.png",
  //   img2: "/images/techdia.png",
  //   title: "Techdia Academy",
  //   link: "https://techdia.vercel.app/",
  //   category: "Frontend",
  //   desc: "Nodejs, Expressjs, NextJS, formik, tailwindcss, yup",
  // },
  // {
  //   img: "/images/beads.png",
  //   img2: "/images/meritbeeds.png",
  //   title: "Merit beads",
  //   link: "https://meritbeeds.vercel.app/",
  //   category: "Fullstack",
  //   desc: "React, Firebase, redux toolkit, tailwindcss, react-table, RTK Query",
  // },
  // {
  //   img: "/images/musknet2.png",
  //   img2: "/images/musknet2.png",
  //   title: "Musknet",
  //   link: "https://musknet.vercel.app/",
  //   category: "Frontend",
  //   desc: "NextJs, firebase, redux toolkit, tailwindcss, axios, swr",
  // },
  {
    img: "/images/bg.jpg",
    img2: "/images/bg.jpg",
    title: "Lexanalytics",
    link: "https://www.lexanalytics.ai/",
    category: "Fullstack",
    desc: "AI-powered legal research, analytics & contract automation",
  },
  {
    img: "/images/bg.jpg",
    img2: "/images/bg.jpg",
    title: "DanceDeal Training Foundation",
    link: "https://dancedeal.org/",
    category: "Fullstack",
    desc: "Online training & registration platform",
  },
  {
    img: "/images/bg.jpg",
    img2: "/images/bg.jpg",
    title: "Dancerapy",
    link: "https://dancerapy.org/",
    category: "Fullstack",
    desc: "Dance fitness video streaming platform",
  },
  {
    img: "/images/bg.jpg",
    img2: "/images/bg.jpg",
    title: "Nuvoro",
    link: "https://nuvoro.net",
    category: "Fullstack",
    desc: "Appointment booking & payment system for service businesses",
  },
  {
    img: "/images/bg.jpg",
    img2: "/images/bg.jpg",
    title: "Stalwartblue",
    link: "https://opticap.stalwartblue.com/",
    category: "Fullstack",
    desc: "Enterprise capital & funding management portal to loans.",
  },
];
