// import alex from "/alex-varela-OEhWh_xz_JM-unsplash.jpg"
export const RWData = [
  {
    img: "/images/create.png",
    img2: "/images/create.png",
    title: "cr8Vibe Media",
    link: "https://cr8vmedia.vercel.app/",
    // action:"",
    category: "Frontend",
    desc: "NextJs, Tailwindcss, react Icons.",
  },
  {
    img: "/images/growthclub.png",
    img2: "/images/growthclubsnap.png",
    title: "Growth Club",
    link: "https://growthclub.life",
    category: "Frontend",
    desc: "chart.js, formik, tailwindcss, yup, react-table, NextJS, TailwindCSS, Redux toolkit, RTK Query.",
  },
  {
    img: "/images/techdia.png",
    img2: "/images/techdia.png",
    title: "Techdia Academy",
    link: "https://techdia.vercel.app/",
    category: "Frontend",
    desc: "Nodejs, Expressjs, NextJS, formik, tailwindcss, yup",
  },
  {
    img: "/images/beads.png",
    img2: "/images/meritbeeds.png",
    title: "Merit beads",
    link: "https://meritbeeds.vercel.app/",
    category: "Fullstack",
    desc: "React, Firebase, redux toolkit, tailwindcss, react-table, RTK Query",
  },
  {
    img: "/images/musknet2.png",
    img2: "/images/musknet2.png",
    title: "Musknet",
    link: "https://musknet.vercel.app/",
    category: "Frontend",
    desc: "NextJs, firebase, redux toolkit, tailwindcss, axios, swr",
  },
  {
    img: "/images/sergey-sokolov-CWFpNqjp_S4-unsplash.jpg",
    img2: "/images/sergey-sokolov-CWFpNqjp_S4-unsplash.jpg",
    // img: {
    //   sm: "/images/sergey-sokolov-CWFpNqjp_S4-unsplash.jpg",
    //   md: "/images/sergey-sokolov-CWFpNqjp_S4-unsplash.jpg",
    //   lg: "/images/sergey-sokolov-CWFpNqjp_S4-unsplash.jpg",
    // },
    title: "Current",
    link: "/",
    category: "Fullstack",
    desc: "This project is for a furniture company. It has not been lunched, hence I can't share the particulars of the company.",
  },
];
